name: github actions to run the test on push to master
run-name: 
on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow
  
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true


jobs:
  test:
      name: Run the echo test
      runs-on: macos-latest
      env:
        MY_TOKEN: ${{ secrets.PAT_TOKEN }}
      steps:
      - name: run single command to echo
        run: echo "Running the test with token as $MY_TOKEN"
        
      - name: Checkout the repo code 
        uses: actions/checkout@v4.2.2
        with:
          # Repository name with owner. For example, actions/checkout
          repository: ${{ github.repository }} # optional, default is ${{ github.repository }
          
      - name: list the files in the directory of github workspace
        run: ls -l
