name: github actions to run the test on push to master
on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow

jobs:
  test:
    runs_on: macos-latest
    steps:
      - run: echo "Running the test"