name: github actions to run the test on push to master
run-name: 
on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow

jobs:
  test:
    name: Run the echo test
    runs-on: macos-latest
    steps:
      name: run single command to echo
      run: echo "Running the test"